markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: LeoGray's White Paper
host: leogray.net
desc: 科技、新奇、好玩

custom:
    category:
        thinking: 思考
        tech:     科技
        another:  其他
        fun:      有趣
        hardware: 硬件
        PM:       产品

    categories:
      - name:  thinking
        title: 思考

      - name:  tech
        title: 科技

      - name:  fun
        title: 有趣

      - name:  hardware
        title: 硬件

      - name:  PM
        title: 产品

      - name:  another
        title: 其他


    scrollingLoadCount: 2                               # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: LeoGray
        email: i@leogray.net
        disqus: leogray7                                # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y         # Google自定义搜索标识ID
#        github: leogray                                 # GitHub账号
        gravatar: 7d159274544ae83eef06f88f11284d00      # Gravatar头像标识

        disqus: https://leogray7.disqus.com/embed.js    # Disqus评论的JS地址
        gapi: http://www.google.com/jsapi               # Google API地址
        gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址

meta:
    author:
        name: LeoGray
        email: i@leogray.net
        disqus: your-disqus-short-name              # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
#        github: your-github-account                 # GitHub账号
        gravatar: 7d159274544ae83eef06f88f11284d00  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
